// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: rpc_create_game_room.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGameRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateGameRoomRequest) Reset() {
	*x = CreateGameRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_game_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRoomRequest) ProtoMessage() {}

func (x *CreateGameRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_game_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRoomRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_game_room_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateGameRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameRoom *GameRoom `protobuf:"bytes,1,opt,name=game_room,json=gameRoom,proto3" json:"game_room,omitempty"`
}

func (x *CreateGameRoomResponse) Reset() {
	*x = CreateGameRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_game_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRoomResponse) ProtoMessage() {}

func (x *CreateGameRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_game_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateGameRoomResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_game_room_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameRoomResponse) GetGameRoom() *GameRoom {
	if x != nil {
		return x.GameRoom
	}
	return nil
}

var File_rpc_create_game_room_proto protoreflect.FileDescriptor

var file_rpc_create_game_room_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x0e, 0x67, 0x61, 0x6d, 0x65, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x2b, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x43, 0x0a,
	0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x72, 0x65, 0x77, 0x5f, 0x30, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_create_game_room_proto_rawDescOnce sync.Once
	file_rpc_create_game_room_proto_rawDescData = file_rpc_create_game_room_proto_rawDesc
)

func file_rpc_create_game_room_proto_rawDescGZIP() []byte {
	file_rpc_create_game_room_proto_rawDescOnce.Do(func() {
		file_rpc_create_game_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_create_game_room_proto_rawDescData)
	})
	return file_rpc_create_game_room_proto_rawDescData
}

var file_rpc_create_game_room_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_game_room_proto_goTypes = []interface{}{
	(*CreateGameRoomRequest)(nil),  // 0: pb.CreateGameRoomRequest
	(*CreateGameRoomResponse)(nil), // 1: pb.CreateGameRoomResponse
	(*GameRoom)(nil),               // 2: pb.GameRoom
}
var file_rpc_create_game_room_proto_depIdxs = []int32{
	2, // 0: pb.CreateGameRoomResponse.game_room:type_name -> pb.GameRoom
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_game_room_proto_init() }
func file_rpc_create_game_room_proto_init() {
	if File_rpc_create_game_room_proto != nil {
		return
	}
	file_gameroom_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_create_game_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_create_game_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_create_game_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_game_room_proto_goTypes,
		DependencyIndexes: file_rpc_create_game_room_proto_depIdxs,
		MessageInfos:      file_rpc_create_game_room_proto_msgTypes,
	}.Build()
	File_rpc_create_game_room_proto = out.File
	file_rpc_create_game_room_proto_rawDesc = nil
	file_rpc_create_game_room_proto_goTypes = nil
	file_rpc_create_game_room_proto_depIdxs = nil
}
