// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddPlayerToGameRoom(ctx context.Context, arg AddPlayerToGameRoomParams) (GameRoomPlayer, error)
	CreateGame(ctx context.Context, gameRoomID uuid.UUID) (Game, error)
	CreateGameRoom(ctx context.Context, createdBy uuid.UUID) (GameRoom, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	FinishGame(ctx context.Context, gameID uuid.UUID) (Game, error)
	GetActiveGame(ctx context.Context, gameRoomID uuid.UUID) (Game, error)
	GetGame(ctx context.Context, gameID uuid.UUID) (Game, error)
	GetGameRoomAndPlayerRows(ctx context.Context, gameRoomID uuid.UUID) ([]GetGameRoomAndPlayerRowsRow, error)
	GetGamesByRoomId(ctx context.Context, gameRoomID uuid.UUID) ([]Game, error)
	GetPlayer(ctx context.Context, playerID uuid.UUID) (Player, error)
	SetActiveGame(ctx context.Context, gameID uuid.UUID) (ActiveGame, error)
	StartGame(ctx context.Context, gameID uuid.UUID) (Game, error)
	UnsetActiveGame(ctx context.Context, gameID uuid.UUID) (UnsetActiveGameRow, error)
}

var _ Querier = (*Queries)(nil)
