// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddGameRoomPlayer(ctx context.Context, arg AddGameRoomPlayerParams) (GameRoomPlayer, error)
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreateGameRoom(ctx context.Context, arg CreateGameRoomParams) (GameRoom, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	Finish(ctx context.Context, id uuid.UUID) error
	GetActiveGameByRoomId(ctx context.Context, gameRoomID uuid.UUID) ([]Game, error)
	GetGame(ctx context.Context, id uuid.UUID) (Game, error)
	GetGameByRoomId(ctx context.Context, gameRoomID uuid.UUID) ([]Game, error)
	GetGameRoom(ctx context.Context, gameRoomID uuid.UUID) (GameRoom, error)
	GetPlayer(ctx context.Context, playerID uuid.UUID) (Player, error)
	StartGame(ctx context.Context, id uuid.UUID) error
	UpdateGame(ctx context.Context, arg UpdateGameParams) error
}

var _ Querier = (*Queries)(nil)
